#include "VTCaptainStandings.h"
#include "VTGameplay.h"
#include "VTSaveSubsystem.h"
FVTCaptainStandings::FAdapter FVTCaptainStandings::Resolve(FGuid Profile) const{if(!Owner||!Profile.IsValid())return {};for(auto It=Owner->GetWorld()->GetPlayerControllerIterator();It;++It)if(auto* PS=It->Get()->GetPlayerState<AVTPlayerState>())if(PS->Profile==Profile)return {&PS->Reputation,&PS->Heat};if(auto* Save=Owner->GetWorld()->GetGameInstance()->GetSubsystem<UVTSaveSubsystem>())if(auto* R=Save->PlayerRecords.FindByPredicate([Profile](const FVTSavedPlayer& P){return P.Profile==Profile;}))return {&R->Reputation,&R->Heat};return {};}
FVTStanding FVTCaptainStandings::Read(FGuid Profile,FName Faction) const{auto A=Resolve(Profile);int I=Owner?Owner->Data->FactionIndex(Faction):-1;return A&&A.Reputation->IsValidIndex(I)&&A.Heat->IsValidIndex(I)?FVTStanding{(*A.Reputation)[I],(*A.Heat)[I],true}:FVTStanding{};}
void FVTCaptainStandings::Crime(FGuid Profile,const AVTShip* V,float Amount){if(!Owner||Owner->GetWorld()->GetNetMode()==NM_Client||!V||Amount<=0)return;auto A=Resolve(Profile);if(!A)return;auto* D=Owner->Data.Get();auto Apply=[&](FName Faction){int I=D->FactionIndex(Faction);if(A.Reputation->IsValidIndex(I)&&A.Heat->IsValidIndex(I)&&(*A.Reputation)[I]>=D->World.hostile_threshold)(*A.Heat)[I]=FMath::Min(100.f,(*A.Heat)[I]+Amount*D->World.heat_per_damage);};Apply(V->Faction);FName SystemOwner=D->Systems[V->SystemIndex].Owner;if(SystemOwner!=V->Faction&&D->StandingBetween(SystemOwner,V->Faction)>=D->World.hostile_threshold)Apply(SystemOwner);}
void FVTCaptainStandings::Rescue(FGuid Profile,FName Faction){if(!Owner||Owner->GetWorld()->GetNetMode()==NM_Client)return;auto A=Resolve(Profile);int I=Owner->Data->FactionIndex(Faction);if(A&&A.Reputation->IsValidIndex(I))(*A.Reputation)[I]=FMath::Min(100.f,(*A.Reputation)[I]+Owner->Data->World.avenge_reputation_bonus);}
void FVTCaptainStandings::Decay(float Dt){if(!Owner||Owner->GetWorld()->GetNetMode()==NM_Client)return;TSet<FGuid> Captains;for(auto It=Owner->GetWorld()->GetPlayerControllerIterator();It;++It)if(auto* PS=It->Get()->GetPlayerState<AVTPlayerState>())if(PS->Profile.IsValid())Captains.Add(PS->Profile);if(auto* Save=Owner->GetWorld()->GetGameInstance()->GetSubsystem<UVTSaveSubsystem>())for(const auto& R:Save->PlayerRecords)Captains.Add(R.Profile);for(FGuid Profile:Captains){auto A=Resolve(Profile);if(!A)continue;for(int I=0;I<A.Heat->Num();++I)if(A.Reputation->IsValidIndex(I)){float Delta=FMath::Min((*A.Heat)[I],Owner->Data->World.heat_decay_per_sec*Dt);(*A.Heat)[I]-=Delta;(*A.Reputation)[I]=FMath::Clamp((*A.Reputation)[I]-Delta*Owner->Data->World.heat_to_reputation_rate,-100.f,100.f);}}}
int32 FVTCaptainStandings::HeatPaymentCost(FGuid Profile,FName Faction) const{auto S=Read(Profile,Faction);return S.Found?FMath::CeilToInt(S.Heat*Owner->Data->Rules.CreditsPerHeat):-1;}
bool FVTCaptainStandings::PayHeat(FGuid Profile,FName Faction,int32& Credits){if(!Owner||Owner->GetWorld()->GetNetMode()==NM_Client)return false;int Cost=HeatPaymentCost(Profile,Faction);if(Cost<0||Credits<Cost)return false;auto A=Resolve(Profile);int I=Owner->Data->FactionIndex(Faction);(*A.Heat)[I]=0;Credits-=Cost;return true;}
