#if WITH_DEV_AUTOMATION_TESTS && WITH_EDITOR
#include "VTIntro.h"
#include "VTGameplay.h"
#include "VTCombat.h"
#include "VTSaveSubsystem.h"
#include "VTIntroWidget.h"
#include "Blueprint/WidgetBlueprintGeneratedClass.h"
#include "Blueprint/WidgetTree.h"
#include "Kismet/GameplayStatics.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "Misc/AutomationTest.h"
namespace {
struct FIntroFixture {
 UWorld* World;UVTGameInstance* GI;UVTSimulation* Sim;AVTController* PC;AVTShip* Ship;
 FIntroFixture(){World=UWorld::CreateWorld(EWorldType::Game,false,FName("VTIntroTests"));auto& Context=GEngine->CreateNewWorldContext(EWorldType::Game);Context.SetCurrentWorld(World);GI=NewObject<UVTGameInstance>(GEngine);GI->InitializeHeadlessWorld(World);GI->PlayMode=TEXT("sandbox");World->SetGameMode(FURL());World->InitializeActorsForPlay(FURL());World->BeginPlay();Sim=World->GetSubsystem<UVTSimulation>();Sim->Bootstrap(0);PC=Captain();Ship=CastChecked<AVTShip>(PC->GetPawn());GI->GetSubsystem<UVTSaveSubsystem>()->Slot=TEXT("IntroAutomation");}
 AVTController* Captain(){auto* C=World->SpawnActor<AVTController>();FVTMotion M;M.Position=FVector2D(0,-270);auto* S=Sim->SpawnShip(TEXT("corsair_frigate"),0,M,false,TEXT("Corsairs"));C->Possess(S);if(auto* PS=C->GetPlayerState<AVTPlayerState>()){PS->Profile=FGuid::NewGuid();PS->Reputation=Sim->Data->InitialReputation;PS->Heat.Init(0,PS->Reputation.Num());}C->Intro->Start();return C;}
 void Step(int N=1){for(int I=0;I<N;++I){Ship->LastInputTime=World->GetRealTimeSeconds();Sim->FixedStep();}}
 ~FIntroFixture(){Sim->Bootstrapped=false;World->BeginTearingDown();GI->Shutdown();World->EndPlay(EEndPlayReason::Quit);World->DestroyWorld(false);GEngine->DestroyWorldContext(World);}
};
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVTIntroRules,"VT.Intro.ProgressRepairsAndCombat",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FVTIntroRules::RunTest(const FString&){
 FIntroFixture F;auto* I=F.PC->Intro.Get();auto* S=F.Ship;TestTrue("Captain begins awake in a private arena",I->Progress.Stage==EVTIntroStage::Wake&&UVTIntroComponent::IsArena(F.Sim,S->SystemIndex));
 FVTPilotIntent Input;Input.Throttle=Input.Turn=1;Input.Buttons=4095;I->Filter(Input);TestTrue("Dead helm and systems reject intent",Input.Throttle==0&&Input.Buttons==0);const int Shots=F.Sim->Projectiles.Num();S->Abilities->TryActivateAbilityByClass(UVTBroadsideAbility::StaticClass());TestEqual("Direct ability request cannot bypass repair",F.Sim->Projectiles.Num(),Shots);
 I->ServerAdvance();I->ServerAdvance();TestTrue("Continue cannot bypass helm lesson",I->Progress.Stage==EVTIntroStage::Helm);
 S->Intent.Throttle=0.5f;S->Intent.Turn=0.5f;F.Step(160);TestTrue("Real flight contributes progress",I->Progress.Distance>0&&I->Progress.Turn>0);I->Progress.Distance=I->Data->HelmDistance;I->Progress.Turn=I->Data->HelmTurn;S->Intent={};S->Movement->Motion.Position=I->Data->ClearPoint;S->Movement->Motion.Velocity=FVector2D::ZeroVector;S->Movement->Motion.Omega=0;F.Step();TestTrue("Move turn halt unlock broadside",I->Progress.Stage==EVTIntroStage::Debris);
 auto* Debris=I->Target.Get();TestNotNull("Live destructible wreck",Debris);S->Movement->Motion.Heading=0;S->Intent.Aim=(I->Data->DebrisPoint-S->Movement->Motion.Position).GetSafeNormal();S->Intent.Buttons=VTButtons::Port;F.Step();for(int N=0;N<600&&I->Progress.Stage==EVTIntroStage::Debris;++N){S->Intent.Buttons=VTButtons::Port;F.Step();}TestTrue("Actual broadside clears debris and starts repairs",I->Progress.Stage==EVTIntroStage::Repairs);TestTrue("Repaired shields and equipment available",I->SystemsOnline());
 F.Step(FMath::CeilToInt(I->Data->RepairSeconds/VT::Step)+1);TestTrue("Engineer offers repair after delay",I->Progress.Stage==EVTIntroStage::BatteryChoice);
 I->ServerChooseRepair(99);TestTrue("Invalid repair leaves stage unchanged",I->Progress.Stage==EVTIntroStage::BatteryChoice);I->ServerChooseRepair(0);TestTrue("Only boost repaired",S->Definition.Equipment.Boost&&!S->Definition.Equipment.EMP);I->ServerChooseRepair(1);TestTrue("Duplicate choice cannot grant second system",!S->Definition.Equipment.EMP);
 S->Intent.Throttle=0.5f;S->Intent.Buttons=VTButtons::Boost;F.Step(70);TestTrue("Actual boost trial unlocks next choice",I->Progress.Stage==EVTIntroStage::SpecialChoice);I->ServerChooseRepair(1);TestTrue("Only microwarp repaired",S->Definition.Equipment.Warp&&!S->Definition.Equipment.Torpedoes);S->Intent={};S->Intent.CursorOffset=FVector2D(80,0);S->Intent.Buttons=VTButtons::Warp;F.Step();S->Intent.Buttons=0;F.Step();TestTrue("Actual microwarp trial unlocks encounter",I->Progress.Stage==EVTIntroStage::Challenge);I->ServerAdvance();auto* Enemy=I->Target.Get();if(!TestNotNull("Enemy spawned",Enemy))return false;
 Enemy->Combat->Damage(Enemy->Attributes->Hull.GetCurrentValue()-Enemy->Definition.Hull*0.2f,Enemy->Movement->Motion.Position,S);F.Step();TestTrue("Normal crippling unlocks boarding",I->Progress.Stage==EVTIntroStage::Salvage);
 const int Credits=F.PC->GetPlayerState<AVTPlayerState>()->Credits;S->Movement->Motion.Position=Enemy->Movement->Motion.Position+FVector2D(0,-80);S->Movement->Motion.Velocity=FVector2D::ZeroVector;Enemy->Movement->Motion.Velocity=FVector2D::ZeroVector;S->Intent.Buttons=VTButtons::Interact;F.Step(260);TestTrue("Held real boarding unlocks gate",I->Progress.Stage==EVTIntroStage::Gate);TestEqual("Intro awards no farmable credits",F.PC->GetPlayerState<AVTPlayerState>()->Credits,Credits);
 auto Centre=F.Sim->JumpPosition(S->SystemIndex,F.Sim->Data->StartSystem);S->Movement->Motion.Position=Centre-Centre.GetSafeNormal()*F.Sim->Data->GateStartDistance();S->Movement->Motion.Heading=FMath::Atan2(Centre.Y,Centre.X);S->Movement->Motion.Velocity=FVector2D::ZeroVector;S->Movement->Motion.Omega=0;S->Intent.Buttons=VTButtons::Interact;
 for(int N=0;N<800&&I->Progress.Stage==EVTIntroStage::Gate;++N)F.Step();TestTrue("Physical gate crossing hands off to sandbox",I->Progress.Stage==EVTIntroStage::Handoff&&!UVTIntroComponent::IsArena(F.Sim,S->SystemIndex));I->ServerAdvance();TestFalse("Silent captain finishes intro",I->Active());return true;
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVTIntroPersistence,"VT.Intro.IsolationSaveReconnectAndSkip",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FVTIntroPersistence::RunTest(const FString&){
 FIntroFixture F;TSet<int32> Arenas;Arenas.Add(F.Ship->SystemIndex);for(int N=0;N<3;++N){auto* C=F.Captain();Arenas.Add(CastChecked<AVTShip>(C->GetPawn())->SystemIndex);}TestEqual("Four independent private spaces",Arenas.Num(),4);
 auto* I=F.PC->Intro.Get();I->Change(EVTIntroStage::Duel);auto* Save=F.GI->GetSubsystem<UVTSaveSubsystem>();Save->CapturePlayer(F.PC);TestTrue("Consistent save with intro captains",Save->Save());auto* PS=F.PC->GetPlayerState<AVTPlayerState>();const FGuid Profile=PS->Profile;const auto Saved=*Save->PlayerRecords.FindByPredicate([Profile](const FVTSavedPlayer& R){return R.Profile==Profile;});
 I->Cleanup();F.PC->UnPossess();F.Ship->Destroy();F.Sim->SimulationTime+=30;F.Ship=Save->RestoreShip(Saved.Ship);F.PC->Possess(F.Ship);I->Restore(Saved.Intro);TestTrue("Reconnect restores duel checkpoint with target",I->Progress.Stage==EVTIntroStage::Duel&&I->Target.IsValid());TestTrue("Held inputs cancelled",F.Ship->Intent.Buttons==0&&F.Ship->InputQueue.IsEmpty());
 F.Ship->Abilities->SetNumericAttributeBase(UVTAttributes::HullAttribute(),0);F.Step();TestTrue("Defeat retries without losing command",F.PC->GetPawn()==F.Ship&&F.Ship->Attributes->Hull.GetCurrentValue()>0&&I->Target.IsValid());
 I->ServerSkip();TestFalse("Skip completes intro",I->Active());TestFalse("Skip exits private arena",UVTIntroComponent::IsArena(F.Sim,F.Ship->SystemIndex));TestEqual("Other captains retained",Arenas.Num(),4);
 TestTrue("Save-load restores connected checkpoints",Save->Load());TestTrue("Loaded captain returned to saved duel",I->Progress.Stage==EVTIntroStage::Duel&&I->Target.IsValid());
 auto* Legacy=NewObject<UVTWorldSave>();FVTSavedPlayer Old;TestTrue("Schema-6 missing checkpoint defaults to complete",Old.Intro.Stage==EVTIntroStage::Complete);Legacy->Players.Add(Saved);TArray<uint8> Bytes;TestTrue("Checkpoint serializes",UGameplayStatics::SaveGameToMemory(Legacy,Bytes));auto* Loaded=Cast<UVTWorldSave>(UGameplayStatics::LoadGameFromMemory(Bytes));TestTrue("Checkpoint round trip",Loaded&&Loaded->Players[0].Intro.Stage==EVTIntroStage::Duel);return true;
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVTIntroAssets,"VT.Intro.AuthoredNarrativeAssets",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FVTIntroAssets::RunTest(const FString&){auto* D=LoadObject<UVTIntroData>(nullptr,TEXT("/Game/Data/DA_Intro.DA_Intro"));if(!TestNotNull("Native intro data",D))return false;TestNotNull("Engineer portrait",D->EngineerPortrait.Get());TestNotNull("Enemy portrait",D->CaptainPortrait.Get());TestEqual("Thirteen playable story beats",D->Beats.Num(),13);TestEqual("Two exclusive battery repairs",D->BatteryRepairs.Num(),2);TestEqual("Two exclusive special repairs",D->SpecialRepairs.Num(),2);auto* BP=Cast<UWidgetBlueprintGeneratedClass>(LoadClass<UVTIntroWidget>(nullptr,TEXT("/Game/UI/WBP_Intro.WBP_Intro_C")));if(TestNotNull("Native UMG widget blueprint",BP)){auto* Tree=BP->GetWidgetTreeArchetype();TestNotNull("Portrait in authored widget tree",Tree?Tree->FindWidget(TEXT("Portrait")):nullptr);TestNotNull("Skip available",Tree?Tree->FindWidget(TEXT("Skip")):nullptr);TestNotNull("First repair button",Tree?Tree->FindWidget(TEXT("ChoiceA")):nullptr);TestNotNull("Second repair button",Tree?Tree->FindWidget(TEXT("ChoiceB")):nullptr);}return true;}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FVTIntroAlternateRepairs,"VT.Intro.EMPAndTorpedoRepairPath",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FVTIntroAlternateRepairs::RunTest(const FString&){FIntroFixture F;auto* I=F.PC->Intro.Get();auto* S=F.Ship;TestTrue("No advance fit inherited",S->Fit.OverrideBatteries&&S->Fit.OverrideSpecials&&S->Fit.Batteries.IsEmpty()&&S->Fit.Specials.IsEmpty());I->Change(EVTIntroStage::BatteryChoice);I->ServerChooseRepair(1);S->Movement->Motion.Position=I->Data->ClearPoint;const auto Delta=I->Data->DebrisPoint-S->Movement->Motion.Position;S->Movement->Motion.Heading=FMath::Atan2(Delta.Y,Delta.X);S->Intent.Buttons=VTButtons::EMP;F.Step(4);TestTrue("Actual EMP firing completes trial",I->Progress.Stage==EVTIntroStage::SpecialChoice);I->ServerChooseRepair(0);S->Intent.Buttons=VTButtons::Torpedo;S->Intent.CursorOffset=I->Data->DebrisPoint-S->Movement->Motion.Position;F.Step(40);S->Intent.Buttons=0;for(int N=0;N<100&&I->Progress.Stage==EVTIntroStage::SpecialTrial;++N)F.Step();TestTrue("Actual torpedo lock-release completes trial",I->Progress.Stage==EVTIntroStage::Challenge);auto* Save=F.GI->GetSubsystem<UVTSaveSubsystem>();Save->CapturePlayer(F.PC);TestTrue("Chosen fit and checkpoint save",Save->Save());TestTrue("Chosen fit and checkpoint reload",Save->Load());S=CastChecked<AVTShip>(F.PC->GetPawn());TestTrue("Only chosen systems survive load",S->Definition.Equipment.EMP&&S->Definition.Equipment.Torpedoes&&!S->Definition.Equipment.Boost&&!S->Definition.Equipment.Warp);return true;}
#endif
