#include "VTShipQueries.h"
#include "VTGameplay.h"
void FVTShipQueries::EnsureMembership() const{if(!Dirty||!Owner||!Owner->Data)return;Systems.SetNum(Owner->Data->Systems.Num());Ids.SetNum(Systems.Num());for(auto& B:Systems)B.Reset();for(auto& M:Ids)M.Reset();for(AVTShip* S:Owner->Ships)if(IsValid(S)&&Systems.IsValidIndex(S->SystemIndex)){Systems[S->SystemIndex].Add(S);Ids[S->SystemIndex].Add(S->PersistentId,S);}Dirty=false;}
void FVTShipQueries::BeginStep(){Dirty=true;SpatialReady=BoardingReady=false;EnsureMembership();}
int32 FVTShipQueries::SystemCount() const{EnsureMembership();return Systems.Num();}
const TArray<AVTShip*>& FVTShipQueries::Ordered(int32 System) const{EnsureMembership();static const TArray<AVTShip*> Empty;return Systems.IsValidIndex(System)?Systems[System]:Empty;}
AVTShip* FVTShipQueries::Find(int32 System,FGuid Id) const{EnsureMembership();auto* S=Ids.IsValidIndex(System)?Ids[System].FindRef(Id):nullptr;return IsValid(S)&&S->SystemIndex==System?S:nullptr;}
void FVTShipQueries::BuildSpatial(){EnsureMembership();Cells.SetNum(Systems.Num());LargestRadius=0;for(auto& System:Cells)for(auto& Cell:System)Cell.Value.Reset();for(int I=0;I<Systems.Num();++I)for(auto* S:Systems[I])if(IsValid(S)&&!S->Docked){const auto P=S->Movement->Motion.Position;Cells[I].FindOrAdd(FIntPoint(FMath::FloorToInt(P.X/128),FMath::FloorToInt(P.Y/128))).Add(S);LargestRadius=FMath::Max(LargestRadius,S->Definition.Radius);}SpatialReady=true;BoardingReady=false;}
void FVTShipQueries::SweptCandidates(int32 System,const FVector2D& Before,const FVector2D& After,float Radius,TArray<AVTShip*>& Out) const{checkf(SpatialReady,TEXT("Projectile queries require the post-contact spatial phase"));Out.Reset();if(!Cells.IsValidIndex(System))return;const double Margin=LargestRadius+Radius;FIntPoint A(FMath::FloorToInt((FMath::Min(Before.X,After.X)-Margin)/128),FMath::FloorToInt((FMath::Min(Before.Y,After.Y)-Margin)/128)),B(FMath::FloorToInt((FMath::Max(Before.X,After.X)+Margin)/128),FMath::FloorToInt((FMath::Max(Before.Y,After.Y)+Margin)/128));for(int Y=A.Y;Y<=B.Y;++Y)for(int X=A.X;X<=B.X;++X)if(const auto* Cell=Cells[System].Find(FIntPoint(X,Y)))Out.Append(*Cell);}
void FVTShipQueries::BuildBoarding(){EnsureMembership();Prizes.SetNum(Systems.Num());for(auto& P:Prizes)P.Reset();for(int I=0;I<Systems.Num();++I)for(auto* S:Systems[I])if(IsValid(S)&&S->Disabled&&!S->Invulnerable)Prizes[I].Add(S);BoardingReady=true;SpatialReady=false;}
const TArray<AVTShip*>& FVTShipQueries::Boarding(int32 System) const{checkf(BoardingReady,TEXT("Boarding queries require the post-destruction phase"));static const TArray<AVTShip*> Empty;return Prizes.IsValidIndex(System)?Prizes[System]:Empty;}
